server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/devguardian_auth
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

asgardeo:
  client-id: ${ASGARDEO_CLIENT_ID:q3hG34FWufohAl2f39sWw7ZsimYa}
  client-secret: ${ASGARDEO_CLIENT_SECRET:JLA7tXbgGKSpakVp6QZ_eeZFw73fdaftBdBpt7CD9Wwa}
  base-url: ${ASGARDEO_BASE_URL:https://api.asgardeo.io/t/orge1hf1}
