server:
  port: 8080

spring:
  application:
    name: devguardian

  datasource:
    url: jdbc:postgresql://localhost:5432/devguardian
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

github:
  client-id: ${GITHUB_CLIENT_ID}
  client-secret: ${GITHUB_CLIENT_SECRET}
  redirect-uri: http://localhost:8080/api/github/callback

devguardian:
  workspace:
    base-path: workspace/repos

groq:
  api:
    key: ${GROQ_API_KEY}

gemini:
  api:
    key: ${GEMINI_API_KEY}