server:
  port: 8080

spring:
  application:
    name: devguardian

  datasource:
    url: jdbc:postgresql://localhost:5432/devguardian
    username: postgres
    password: Ananda1886
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true