server:
  port: 8084

spring:
  application:
    name: ai-service

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

ai:
  provider: groq

groq:
  api:
    key: ${GROQ_API_KEY:}
    model: ${GROQ_MODEL:llama-3.3-70b-versatile}

gemini:
  api:
    key: ${GEMINI_API_KEY:}
    model: ${GEMINI_MODEL:gemini-2.0-flash}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000