server:
  port: 8080

spring:
  application:
    name: devguardian-gateway
  codec:
    max-in-memory-size: 150MB
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_LAST
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: repository-service-github
          uri: lb://repository-service
          predicates:
            - Path=/api/github/**
        - id: repository-service-repos
          uri: lb://repository-service
          predicates:
            - Path=/api/repositories/**
        - id: analysis-service
          uri: lb://analysis-service
          predicates:
            - Path=/api/analysis/**, /api/analyses/**
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/ai/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**, /api/notifications/**

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
